// <auto-generated />
using System;
using LibrarySystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibrarySystem.Migrations.LibraryContext
{
    [DbContext(typeof(LibraryDBContext))]
    [Migration("20191114151915_InitialLibraryDBContext")]
    partial class InitialLibraryDBContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibrarySystem.Models.Authors", b =>
                {
                    b.Property<int>("AuthorsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorsName");

                    b.Property<string>("Biography");

                    b.HasKey("AuthorsID");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("LibrarySystem.Models.Books", b =>
                {
                    b.Property<int>("BooksID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorsID");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("PublishName");

                    b.Property<string>("Title");

                    b.HasKey("BooksID");

                    b.HasIndex("AuthorsID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibrarySystem.Models.LibrarySystemRun", b =>
                {
                    b.Property<int>("LibraryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BooksID");

                    b.Property<DateTime>("BorrowedDate");

                    b.Property<DateTime>("DateBack");

                    b.Property<string>("Descriptions");

                    b.Property<int>("LengthBorrowed");

                    b.Property<int>("PersonID");

                    b.HasKey("LibraryID");

                    b.HasIndex("BooksID");

                    b.HasIndex("PersonID");

                    b.ToTable("LibrarySystemRuns");
                });

            modelBuilder.Entity("LibrarySystem.Models.Maritals", b =>
                {
                    b.Property<int>("MaritalID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaritalsName");

                    b.HasKey("MaritalID");

                    b.ToTable("Maritals");
                });

            modelBuilder.Entity("LibrarySystem.Models.Persons", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<int>("MaritalID");

                    b.Property<string>("PersonName")
                        .IsRequired();

                    b.Property<int>("PhoneNumber");

                    b.Property<int>("ReligionID");

                    b.Property<int>("SexID");

                    b.HasKey("PersonID");

                    b.HasIndex("MaritalID");

                    b.HasIndex("ReligionID");

                    b.HasIndex("SexID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("LibrarySystem.Models.Religions", b =>
                {
                    b.Property<int>("ReligionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReligionName");

                    b.HasKey("ReligionID");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("LibrarySystem.Models.Sexs", b =>
                {
                    b.Property<int>("SexID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SexName");

                    b.HasKey("SexID");

                    b.ToTable("Sexs");
                });

            modelBuilder.Entity("LibrarySystem.Models.Books", b =>
                {
                    b.HasOne("LibrarySystem.Models.Authors", "Authories")
                        .WithMany()
                        .HasForeignKey("AuthorsID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LibrarySystem.Models.LibrarySystemRun", b =>
                {
                    b.HasOne("LibrarySystem.Models.Books", "Bookis")
                        .WithMany()
                        .HasForeignKey("BooksID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LibrarySystem.Models.Persons", "Persons")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LibrarySystem.Models.Persons", b =>
                {
                    b.HasOne("LibrarySystem.Models.Maritals", "Maritals")
                        .WithMany()
                        .HasForeignKey("MaritalID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LibrarySystem.Models.Religions", "Religions")
                        .WithMany()
                        .HasForeignKey("ReligionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LibrarySystem.Models.Sexs", "Sexs")
                        .WithMany()
                        .HasForeignKey("SexID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
